### ISSUE TITLE
关于python中 Web3.isChecksumAddress方法问题

### ISSUE THREAD

**Issue by zhanglonglongSH** [AlayaNetwork/client-sdk-python#3]
发现Web3.isChecksumAddress  方法体 直接返回true,不能判断地址,请查看

def is_checksum_address(val):
    return True

**Comment by liyuanchaoCh** [comment]
该问题为历史遗留问题，此方法为校验以太坊地址是否合法，已不再维护，请使用Web3.isAddress接口进行地址合法性校验，后期我们会从文档中移除Web3.isChecksumAddress相关的描述。
