### ISSUE TITLE
关于 getAddressHrp 方法问题

### ISSUE THREAD

**Issue by zhanglonglongSH** [AlayaNetwork/client-sdk-python#4]
w3 = Web3(HTTPProvider("http://47.241.91.2:6789"),chain_id = 201030)
alaya = PlatON(w3)
print(alaya.getAddressHrp)

Traceback (most recent call last):
  File "/Users/longlongzhanq/spider_product/Platon_alaya/test.py", line 20, in <module>
    print(alaya.getAddressHrp)
AttributeError: 'PlatON' object has no attribute 'getAddressHrp'
[]
查看源码没找到这个方法

**Comment by liyuanchaoCh** [comment]
你用的那个分支的代码做的测试呢？如果是alaya分支，alaya分支不支持，可以用develop分支做测试。麻烦后面提issue的时候请把对应的分支写上吧，便于回答你的问题

**Comment by zhanglonglongSH** [comment]
我是直接用的pip安装的，默认安装的是那个分支？版本是1.0.0.2

**Comment by liyuanchaoCh** [comment]
等后面更新吧，1.0.0.2是alaya分支打打包，后面在issue中加上版本号

**Comment by zhanglonglongSH** [comment]
好的 谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AlayaNetwork/client-sdk-python"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月5日(星期四) 上午10:46
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [AlayaNetwork/client-sdk-python] 关于 getAddressHrp 方法问题 (#4)





 
等后面更新吧，1.0.0.2是alaya分支打打包，后面在issue中加上版本号
 
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
